- name: Create disk(s)
  gcp_compute_disk:
    name: "{{ item.name }}"
    size_gb: 20
    #source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts
    #source_image: projects/debian-cloud/global/images/family/debian-8
    source_image: projects/centos-cloud/global/images/family/centos-7
    zone: "{{ gcpinfra_zone }}"
    project: "{{ gcpinfra_project }}"
    auth_kind: "{{ gcpinfra_cred_kind }}"
    service_account_file: "{{ gcpinfra_cred_file }}"
    state: present
  with_items: "{{ gcpinfra_disks_info }}"   
  register: disks

- debug:
    msg: "{{ disks }}"  

- name: Create a network
  gcp_compute_network:
    name: 'myweb-network'
    project: "{{ gcpinfra_project }}"
    auth_kind: "{{ gcpinfra_cred_kind }}"
    service_account_file: "{{ gcpinfra_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: present
  register: network 

- debug:
    msg: "{{ network }}"  

- name: Create  addresses
  gcp_compute_address:
    name: "{{ item.name }}"
    region: "{{ gcpinfra_region }}"
    project: "{{ gcpinfra_project }}"
    auth_kind: "{{ gcpinfra_cred_kind }}"
    service_account_file: "{{ gcpinfra_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: present
  with_items: "{{ gcpinfra_address_info }}"  
  register: addresses

- debug:
    msg: "{{ addresses }}"

- name: Create instance webserver1
  gcp_compute_instance:
    state: present
    name: webserver1
    machine_type: n1-standard-1
    disks:
    - auto_delete: true
      boot: true
      source: "{{ disks.results[0] }}"
    network_interfaces:
    - network: "{{ network }}"
      access_configs:
      - name: 'External NAT'
        nat_ip: "{{ addresses.results[0] }}"
        type: 'ONE_TO_ONE_NAT'
    zone: "{{ gcpinfra_zone }}"
    project: "{{ gcpinfra_project }}"
    auth_kind: "{{ gcpinfra_cred_kind }}"
    service_account_file: "{{ gcpinfra_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute           
  register: webserver1   

- debug:
    msg: "{{ webserver1 }}"

- debug:
    msg: "{{ addresses.results[0] }}"

- name: Add host to web servers group
  add_host: hostname={{ addresses.results[0].address}} groupname=web_servers

- name: Create instance webserver2
  gcp_compute_instance:
    state: present
    name: webserver2
    machine_type: n1-standard-1
    disks:
    - auto_delete: true
      boot: true
      source: "{{ disks.results[1] }}"
    network_interfaces:
    - network: "{{ network }}"
      access_configs:
      - name: 'External NAT'
        nat_ip: "{{ addresses.results[1] }}"
        type: 'ONE_TO_ONE_NAT'
    zone: "{{ gcpinfra_zone }}"
    project: "{{ gcpinfra_project }}"
    auth_kind: "{{ gcpinfra_cred_kind }}"
    service_account_file: "{{ gcpinfra_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute           
  register: webserver2

- debug:
    msg: "{{ webserver2 }}"    

- name: Add host to web servers group
  add_host: hostname={{ addresses.results[1].address}} groupname=web_servers

- name: Create instance dbserver1
  gcp_compute_instance:
    state: present
    name: dbserver1
    machine_type: n1-standard-1
    disks:
    - auto_delete: true
      boot: true
      source: "{{ disks.results[2] }}"
    network_interfaces:
    - network: "{{ network }}"
      access_configs:
      - name: 'External NAT'
        nat_ip: "{{ addresses.results[2] }}"
        type: 'ONE_TO_ONE_NAT'
    zone: "{{ gcpinfra_zone }}"
    project: "{{ gcpinfra_project }}"
    auth_kind: "{{ gcpinfra_cred_kind }}"
    service_account_file: "{{ gcpinfra_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute           
  register: dbserver1

- debug:
    msg: "{{ dbserver1 }}"  

- name: Add host to db servers group
  add_host: hostname={{ addresses.results[2].address}} groupname=db_servers    

- name: create a firewall
  gcp_compute_firewall:
    name: myweb-firewall
    network: "{{ network }}"
    allowed:
    - ip_protocol: tcp
      ports:
      - '22'
      - '80'
    project: "{{ gcpinfra_project }}"
    auth_kind: "{{ gcpinfra_cred_kind }}"
    service_account_file: "{{ gcpinfra_cred_file }}"
    state: present    

 
